data:
    name: homographies
    data_dir: step1-matching-train/step1-matching-train
    train_size: 16560
    val_size: 0
    batch_size: 32
    num_workers: 4
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
data_val:
    name: homographies
    data_dir: first-step-val-dataset/first_step_val_dataset
    train_size: 0
    val_size: 1656
    batch_size: 32
    num_workers: 4
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
model:
    name: two_view_pipeline
    extractor:
        name: gluefactory_nonfree.superpoint
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.0
        nms_radius: 3
        trainable: True
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        flash: false
        checkpointed: true
train:
    seed: 0
    epochs: 5
    log_every_iter: 100
    eval_every_iter: 500
    lr: 1e-5
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']

